api/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('eat/check/participant/<participant_id>/', views.check_user_eat1, name='check_func'),
    path('eat/check/participant/<jour>/<periode>/<participant_id>/', views.check_user_eat2, name='check_func2'),
    path('eat/register/participant/<jour>/<periode>/<participant_id>/', views.set_user_eat1, name='register_func'),

    path('eat/stats/', views.eat_global_stats, name="global_stats"),
    path('eat/stats/<str:jour>/<str:periode>/', views.eat_stats, name="stats"),
    path('eat/stats/<str:jour>/<str:periode>/liste', views.stats_liste, name="stats_liste"),
    path('eat/stats/orga/', views.orga_eat_history, name="orga_eat_history"),

    path('eat/get/stats/<str:jour>/<str:periode>/', views.get_eat_stats, name="get_stats"),
    path('eat/get/stats/', views.get_global_eat_stats, name="get_global_stats"),


]

organisateur/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'organisateur'
urlpatterns = [
    path('accueil/', views.accueil, name='accueil'),
    path("connexion/", views.connexion, name='connexion'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),


    path('selectiones/listes/repartition',views.liste_re,name='liste_re'),
    path('selectiones/listes/<str:niveau>/',views.liste_se,name='liste_se'),
    path('preselection/listes/<str:niveau>/',views.liste_pre_niveau1,name='liste_pre'),

  	#path('problemes/inscription/', views.inscription_problemes, name='inscription_problemes'),

    path('equipes/<id>/', views.equipe_profil, name='equipe_profil'),
]

technohack/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('@c2e/v2/admin/hack20/', admin.site.urls),
    path('', views.accueil, name="accueil"),
    path('resultats/', views.resultats, name='attente'),
    #path('test/resultats/', views.resultats, name='attente'),

    path('equipes/', views.equipes, name='equipes'),
    path('contact/', views.contact, name='contact'),
    path('participant/', include('participant.urls')),
    path('@c2e/v2/orga/app/', include('organisateur.urls')),
	path('preselections/<str:niveau>/',views.liste_pre_niveau1,name='gb_liste_pre'),

    path('api/',include('api.urls'))

    #path('test/',views.test),
]

organisateur/models.py
from django.db import models
from django.contrib.auth.models import User


class Organisateur(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

organisateur/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Organisateur
from participant.models import Participant, Equipe
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse


niveau_list = ["niveau1","niveau2","niveau3","all"]

niveaux_label = {
    "niveau1" : "Niveau 1",
    "niveau2" : "Niveau 2",
    "niveau3" : "Niveau 3"
}

def get_equipes(equipes_data):
    equipes = []
    j = 1
    for i, e in enumerate(equipes_data):
        equipe = {}
        equipe["nom"] = e.nom
        equipe["niveau"] = e.niveau
        equipe["participants"] = []

        for participant in e.participants.all():

            p = {
                'i': j,
                'pk': participant.id,
                'nom': str(participant)
            }

            j += 1

            equipe["participants"].append(p)

        equipes.append(equipe)

    print(equipes)

    return equipes


@login_required(login_url="organisateur:connexion")
def liste_pre_niveau1(request,niveau=""):

    if not request.user.is_staff:
            return redirect('accueil')

    niveau_salle_config_pre_selection = {
        "niveau1": 4,
        "niveau2": 5,
        "niveau3": 5,
    }

    salles = ["A","B","C","D","E","F","G","H"]

    if not niveau in niveaux_label.keys():
        raise Http404("Niveau incorrecte")

    niveau_key = niveau
    niveau = niveaux_label[niveau]

    equipes_data = Equipe.objects.filter(niveau=niveau).order_by('date_creation')

    nbr_equipe_by_salle = niveau_salle_config_pre_selection[niveau_key]

    equipes = []


   # print(equipes)

    return render(request,'organisateur/liste_participants_niveau1.html',locals())


@login_required(login_url="organisateur:connexion")
def liste_se(request,niveau=""):
    if not request.user.is_staff:
        return redirect('accueil')

    if not niveau in niveau_list:
        raise Http404("Niveau inconnue")

    if niveau != "all":
        niveau = niveaux_label[niveau]
        equipes_data = Equipe.objects.filter(niveau=niveau,selectionner=True).order_by('niveau','nom')

    else:
        niveau = "Tous les niveaux"
        equipes_data = Equipe.objects.filter(selectionner=True).order_by('niveau','nom')

    equipes = get_equipes(equipes_data)

    print(equipes)

    return render(request,'organisateur/liste_selectionnes.html',locals())



def is_valid_query_parameter(param):
    return param != '' and param is not None


@login_required(login_url="organisateur:connexion")
def liste_re(request):
    if not request.user.is_staff:
        return redirect('accueil')

    equipes_n1 = get_equipes(Equipe.objects.filter(niveau="Niveau 1",selectionner=True).order_by('nom'))
    equipes_n2 = get_equipes(Equipe.objects.filter(niveau="Niveau 2",selectionner=True).order_by('nom'))
    equipes_n3 = get_equipes(Equipe.objects.filter(niveau="Niveau 3",selectionner=True).order_by('nom'))

    return render(request,"organisateur/liste_equipes_selectionnees.html",locals())



def is_valid_query_parameter(param):
    return param != '' and param is not None


@login_required(login_url="organisateur:connexion")
def accueil(request):

    if not request.user.is_staff:
        return redirect('accueil')

    equipes = Equipe.objects.all().order_by('niveau','date_creation')

    n1 = equipes.filter(niveau='Niveau 1').count()
    n2 = equipes.filter(niveau='Niveau 2').count()
    n3 = equipes.filter(niveau='Niveau 3').count()
    n  = n1 + n2 + n3

    if request.method == 'GET':
        participants = Participant.objects.all()
        equipe_query = request.GET.get('equipe')
        participant_query = request.GET.get('participant')
        etat_query = request.GET.get('etat')
        niveau_equipe = request.GET.get('niveau')

        if is_valid_query_parameter(niveau_equipe) and niveau_equipe != 'Choisir...':
            equipes = equipes.filter(niveau=niveau_equipe)

        if is_valid_query_parameter(equipe_query):
            equipes = equipes.filter(nom__icontains=equipe_query)

        if is_valid_query_parameter(participant_query):
            participants = participants.filter(
                user__last_name__icontains=participant_query)
            print(participants)
            equipes = [participant.equipe for participant in participants]
            equipes_unique = []
            for equipe in equipes:
                if equipe not in equipes_unique:
                    equipes_unique.append(equipe)
            equipes = equipes_unique

        if is_valid_query_parameter(etat_query) and etat_query != 'Choisir...':
            if etat_query == 'selectionnee':
                equipes = equipes.filter(selectionner=True)
            else:
                equipes = equipes.filter(selectionner=False)

        return render(request, 'organisateur/accueil.html', locals())

    if request.method == 'POST':
        equipes = [equipe for equipe in equipes]

        for equipe in equipes:
            index = equipes.index(equipe)
            selectionneur = "selectionner_{}".format(index + 1)
            if request.POST.get(selectionneur) == 'selectionnee':
                equipe.selectionner = True
            else:
                equipe.selectionner = False
            equipe.save()

        equipes = Equipe.objects.all().order_by('date_creation')

        return render(request, 'organisateur/accueil.html', locals())

    return render(request, 'organisateur/accueil.html', locals())


def connexion(request):
    context = {
        'data': request.POST,
        'has_error': False
    }
    if request.method == 'POST':
        login = request.POST.get('login')
        password = request.POST.get('password')

        user = auth.authenticate(username=login, password=password)

        if user is not None:
            auth.login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('organisateur:accueil')
        else:
            messages.add_message(request, messages.ERROR,
                                 "login ou mot de passe incorrect")
            context['has_error'] = True

        if context['has_error']:
            return render(request, 'connexion.html', context)

    return render(request, 'organisateur/connexion.html')

@login_required(login_url="participant:connexion")
def equipe_profil(request, id):

    if not request.user.is_staff:
        return redirect('accueil')

    equipe = get_object_or_404(Equipe, id=id)

    participants = equipe.participants.all

    return render(request, 'organisateur/equipe.html', locals())


@login_required(login_url="participant:connexion")
def inscription_problemes(request): 

    if not request.user.is_superuser:
        return redirect('accueil')

    users = User.objects.all()
    equipes = Equipe.objects.all()

    fake_users = []
    fake_equipes = []

    for user2 in users:
        try:
            user2.participant
        except:
            fake_users.append(user2)

    for equipe in equipes:
        if equipe.chef == "":
            fake_equipes.append(equipe)

    return render(request,"organisateur/inscription.probs.html",locals())


def deconnexion(request):
    auth.logout(request)
    return redirect('accueil')

organisateur/templates/organisateur/accueil.html
{% extends "base.html" %} 

{% block title %}
  Organisateur
{% endblock title %}

{% block content %}
<div class="card">
  <div class="card-header">
    Statistiques
  </div>
  <div class="card-body">
    <div>Niveau 1: <span class="text-primary font-weight">{{ n1 }}</span></div>
    <div>Niveau 2: <span class="text-primary font-weight">{{ n2 }}</span></div>
    <div>Niveau 3: <span class="text-primary font-weight">{{ n3 }}</span></div>
    <div><strong>Total: <span class="text-primary font-weight">{{ n }}</span></strong></div>
  </div>
</div>
<div class="mt-5 text-center">
  <h2>Liste des participants</h2>
</div>
<div class="px-1">
  <div class="mt-5">
    <div class="col-sm-12 col-md-7 mx-auto">
      <!--Filtrer les recherches-->
      <div class="filter mb-5">
        <div class="card py-5 px-5">
          <form method="GET">
            <div class="form-row">
              <div class="form-group col-12">
                <div class="input-group">
                  <input
                    type="search"
                    class="form-control py-2 border-right-0 border"
                    name="participant"
                    placeholder="Participant"
                  />
                  <span class="input-group-append">
                    <div class="input-group-text bg-transparent">
                      <i class="fas fa-search"></i>
                    </div>
                  </span>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-12">
                <div class="input-group">
                  <input
                    type="search"
                    class="form-control py-2 border-right-0 border"
                    name="equipe"
                    placeholder="Equipe"
                  />
                  <span class="input-group-append">
                    <div class="input-group-text bg-transparent">
                      <i class="fas fa-search"></i>
                    </div>
                  </span>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md">
                <label for="annee_academique">Etat de l'équipe</label>
                <select id="etat" class="form-control" name="etat">
                  <option selected>Choisir...</option>
                  <option value="selectionnee">Sélectionnée</option>
                  <option value="eliminee">Eliminée</option>
                </select>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md">
                <label for="niveau">Niveau</label>
                <select id="niveau" class="form-control" name="niveau">
                  <option selected>Choisir...</option>
                  <option value="Niveau 1">Niveau 1</option>
                  <option value="Niveau 2">Niveau 2</option>
                  <option value="Niveau 3">Niveau 3</option>
                </select>
              </div>
            </div>

            <button
              type="submit"
              style="border-radius: 4px;"
              class="btn btn-primary"
            >
              Chercher
            </button>
            <button
              type="submit"
              style="border-radius: 4px;"
              class="btn btn-danger ml-2"
            >
              Tout
            </button>
          </form>
        </div>
      </div>
    </div>

    <div class="table-responsive-xl text-nowrap">
      <form action="" method="POST">
        {% csrf_token %}
        <table class="table table-bordered table-dark table-hover">
          <thead>
            <tr class="text-center">
              <th>#</th>
              <th>Equipe</th>
              <th>Membres</th>
              <th>Niveau</th>
              <th>Etat</th>
              <th>Date création</th>
              <th>Selectionner</th>
            </tr>
          </thead>
          <tbody class="text-center">
            {% for equipe in equipes %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>{{equipe.nom.capitalize}}</td>
              <td>
                <ul style="list-style: none;">
                  {% for participant in equipe.participants.all %}
                  <li>
                    {{participant.user.last_name.capitalize}}
                    {{participant.user.first_name.capitalize}}
                  </li>
                  {% endfor %}
                </ul>
              </td>
              <td>{{equipe.niveau}}</td>
              {% if equipe.selectionner %}
              <td class="bg-success">Selectionée</td>
              {% else %}
              <td class="bg-danger">Eliminée</td>
              {% endif %}
              <td>{{equipe.date_creation}}</td>
              <td>
                <div> 
                    <select class="browser-default custom-select" name="selectionner_{{forloop.counter}}">
                    <option value="{% if equipe.selectionner %}selectionnee{% else %}eliminee{% endif %}">{% if equipe.selectionner %}Sélectionnée{% else %}Eliminée{% endif %}</option>
                    <option value="{% if equipe.selectionner %}eliminee{% else %}selectionnee{% endif %}">{% if equipe.selectionner %}Eliminée{% else %}Sélectionnée{% endif %}</option>
                  </select>
                </div>
                <div class="mt-1">
                  <a href="{% url 'organisateur:equipe_profil' equipe.pk %}" class="btn btn-block btn-sm btn-primary">Afficher</a>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <button type="submit" class="btn btn-primary">
          Enregistrer
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

organisateur/templates/organisateur/connexion.html
{% extends 'base.html' %} 
{% block title %}
  Connexion
{% endblock title %}

{% block content %} {% load static %}
<style>
  body {
    background: url('{% static 'images/bg.png' %}') no-repeat;
    background-size: cover;
  }
</style>

<div>
  <form
    method="POST"
    class="text-center col-md-5 col-sm-8 mx-auto border border-light mt-5 p-5 wow fadeIn"
    data-wow-delay="0.5s"
    action="."
    style="background-color: rgba(255, 255, 255, 0.8);"
  >
    {% csrf_token %}
    <p style="font-size: 60px;"><i class="fas fa-user-tie"></i></p>
    <p class="h4 mb-4">Connexion organisateur</p>

    <div class="md-form md-outline mx-auto">
      <input
        type="text"
        id="login"
        name="login"
        class="form-control bg-white"
      />
      <label for="login">Login</label>
    </div>

    <div class="md-form md-outline mx-auto">
      <input
        type="password"
        id="password"
        name="password"
        class="form-control bg-white"
      />
      <label for="password">Mot de passe</label>
    </div>
    {% if request.GET.next %}
      <input
        type="hidden"
        name="next"
        value="{{request.GET.next}}"
      />
    {% endif %}
    <div class="d-flex justify-content-around">
      <div>
        <!-- Forgot password -->
        <a href="">Mot de passe oublié?</a>
      </div>
    </div>
    <!-- Sign in button -->
    <button class="btn btn-black my-4" type="submit">
      Connexion
    </button>
  </form>
</div>

{% endblock content %}

organisateur/templates/organisateur/edit_table_orga.eat.html
<style>
    .eat{
        background-color: #DCEDC8;
        border-color:#DCEDC8;
        color: #DCEDC8
    }

    .no-eat{
        background: #FFCDD2;
        border-color:#FFCDD2;
        color: #FFCDD2
    }

    .table-bordered td, .table-bordered th {
        border: 1px solid #afafaf;
    }
    .status{
        text-align: center;
    }
</style>
<div class="h3">Tableau du suivi des repas</div>
<table id="table-suivi" class="table table-bordered ">
    <thead>
        <tr>
            <th>#</th>
            <th>Nom</th>
            <th>Vendredi Soir</th>
            <th>Samedi Matin</th>
            <th>Samedi Midi</th>
            <th>Samedi Soir</th>
            <th>Dimanche Matin</th>
            <th>Dimanche Midi</th>
            <th>Date dernier repas</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <form action="" method="POST">
            {% csrf_token %}
            <tr>
                <th>New</th>
                <td class="status">
                    <input type="text" name="orga_name" class="form-control form-control-sm" placeholder="Nom" required>
                </td>
                <td class="status">
                     <input type="checkbox" name="vendredi_soir">
                </td>
                <td class="status">
                     <input type="checkbox" name="samedi_matin">
                </td>
                <td class="status">
                    <input type="checkbox" name="samedi_midi">
                </td>
                <td class="status">
                    <input type="checkbox" name="samedi_soir">
                </td>
                <td class="status">
                    <input type="checkbox" name="dimanche_matin">
                </td>
                <td class="status">
                    <input type="checkbox" name="dimanche_midi">
                </td>
                <td class="bg-light"></td>
                <td class="status">
                    <button class="btn btn-dark btn-sm" name="add">Ajouter</button>
                </td>
            </tr>
        </form>
        <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% for orga in organisateurs %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ orga.nom }}</td>
                <td class="status  {% if orga.vendredi_soir == True %}  eat {% else %} no-eat {% endif %}">
                    <input type="checkbox" name="vendredi_soir_{{ forloop.counter0 }}"  {% if orga.vendredi_soir == True %} checked="checked" {% endif %}>
                </td>

                <td class="status  {% if orga.samedi_mati == True %}  eat {% else %} no-eat {% endif %}">
                    <input type="checkbox" name="samedi_matin_{{ forloop.counter0 }}"  {% if orga.samedi_matin == True %} checked="checked" {% endif %}>
                </td>
                <td class="status  {% if orga.samedi_midi == True %}  eat {% else %} no-eat {% endif %}">
                    <input type="checkbox" name="samedi_midi_{{ forloop.counter0 }}"  {% if orga.samedi_midi == True %} checked="checked" {% endif %}>
                </td>
                <input type="hidden" name="samedi_midi_{{ forloop.counter0 }}"  {% if orga.samedi_midi == True %} checked="checked" {% endif %}>
                <td class="status  {% if orga.samedi_soir == True %}  eat {% else %} no-eat {% endif %}">
                    <input type="checkbox" name="samedi_soir_{{ forloop.counter0 }}"  {% if orga.samedi_soir == True %} checked="checked" {% endif %}>
                </td>
                <td class="status  {% if orga.dimanche_matin == True %}  eat {% else %} no-eat {% endif %}">
                    <input type="checkbox" name="dimanche_matin_{{ forloop.counter0 }}"  {% if orga.dimanche_matin == True %} checked="checked" {% endif %}>
                </td>
                <td class="status  {% if orga.dimanche_midi == True %}  eat {% else %} no-eat {% endif %}">
                     <input type="checkbox" name="dimanche_midi_{{ forloop.counter0 }}"  {% if orga.dimanche_midi == True %} checked="checked" {% endif %}>
                </td>
                <td>
                    {{ orga.date }}
                    <input type="hidden" name="orga_{{ forloop.counter0 }}" value="{{ orga.pk }}">
                </td>
                <td class="status">
                    <a href="#"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div class="p-1">
    <button class="btn btn-primay" type="submit" name="register">ENREGISTRER</button>
</div>
</form>

organisateur/templates/organisateur/equipe.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
  Profile
{% endblock title %}


{% block content %} 

<h2 class="text-center my-3">{{equipe.nom.upper}}</h2>
<div class="mb-5">
    <div class="container-fluid" style="position: relative; top: 80px;">
        <div class="row">
            <div class="col-md-4 col-lg-3">
                <section class="card profile-card mb-5">
                    <div
                        class="avatar z-depth-1-half w-25 rounded-circle mx-auto bg-white"
                        style="margin-top: -60px;"
                    >
                        <img
                        src="{% static 'images/icone.png' %}"
                        width="150"
                        height="auto"
                        alt=""
                        class="img-fluid rounded-circle"
                        />
                    </div>
                    <div class="card-body">
                        <div class="text-center">
                           <h4>Equipe {{ equipe.pk }} - {{equipe.niveau}}</h4>
                        </div>
                        <hr>
                        <p class="card-text mt-3">
                        <h5>Nom d'équipe : <sapn class="text-warning">{{equipe.nom.upper}}</span></h5>
                        <h5>Chef : <sapn>{{equipe.chef.upper}}</span></h5>
                        <h5>Etat : {% if user.participant.equipe.selectionner %}<span class="text-success">Sélectionnée</span>{% else %}<span class="text-danger">Eliminée</span>{% endif %} </h5> 
                        </p>
                    </div>
                </section>
            </div>
            {% for participant in participants %}
            <div class="col-sm-12 col-md-4 col-lg-3">
                {% include 'organisateur/equipe.participant.html' %}
            </div>  
            {% endfor %}    
        </div>
    </div>
</div>
<div class="text-center text-muted m-3">&copy Technovore Hackathon 2020</div>
{% endblock content %}

organisateur/templates/organisateur/equipe.participant.html
{% load static %}

<section class="card profile-card mb-5 {% if not participant.is_chief %} border{% endif %}">
    <div class="card-header d-flex justify-content-between">
        <div>
        {% if participant.is_chief == True %}
            Chef d'équipe
        {% else %}
            Coéquipier
        {% endif %}
        </div>
        <div><strong class="">Numéro: #{{ participant.pk }}</strong></div>
    </div>
    <div class="card-body">
        <h5 class="card-title">
            {{participant.user.last_name.capitalize}} {{participant.user.first_name.capitalize}}
        </h5>
        <div>Nom d'utilisateur : <span class="text-info">{{participant.user.username}}</span></div>
        <hr>
        <div>Email : <span class="text-info">{{participant.user.email}}</span></div>
        <div>Numéro : <span class="text-info">{% if participant.numero %}{{participant.numero}}{% endif %}</span></div>
    </div>
</section>

organisateur/templates/organisateur/history.eat.html
{% extends 'organisateur/base.eat.html' %}

{% block content %}

<div id="menu-btn" class="p-3"><a href="#"><span class="techno-orange"><i class="fa fa-bars"></i></span></a></div>
<div class="container-fluid">
    <div class="row">
        <div id="menu" class="col-sm-12 col-md-12 col-lg-3 c p-4 pt-5 border-right">
            {% include 'organisateur/nav.eat.html'  %}
        </div>
        <div id="stats" class="col-sm-12 Col-md-12 col-lg-9">
            <nav>
              <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="false">Bilan</a>
                <a class="nav-item nav-link active" id="nav-edit-tab" data-toggle="tab" href="#nav-edit" role="tab" aria-controls="nav-edit" aria-selected="false">Gestion du tableau de suivi</a>
                <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="true">Tableau de suivi</a>
              </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                  <div class="h3">Bilan Général</div>
              </div>
              <div class="tab-pane fade show active" id="nav-edit" role="tabpanel" aria-labelledby="nav-edit-tab">
                  {% include 'organisateur/edit_table_orga.eat.html' %}
              </div>
                <div class="tab-pane" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                  {% include 'organisateur/table_orga.eat.html' %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

organisateur/templates/organisateur/inscription.probs.html
{% extends "base.html" %}


{% block content %}
<div class="container p-4">
	<h1>Utilisateurs </h1>
	<ul>
		{% for user in fake_users %}
			{% if not user.is_staff %}
			<li>
				<ul>
					<li>ID: {{ user.pk}}</li>
					<li>Nom utilisateur: {{ user.username }}</li>
					<li>Nom: {{ user.first_name }}</li>
					<li>Prenom: {{ user.last_name }}</li>
				</ul>
			</li>
			{% endif %}

		
		{% endfor %}
	</ul>
	<div class="mt-5">
		<h1>Equipes sans participant </h1>
		<ul>
			{% for equipe in fake_equipes %}
				<li>
					<ul>
						<li>ID: {{ equipe.pk}}</li>
						<li>Nom : {{ equipe.nom }}</li>
						<li>Niveau : {{ equipe.niveau }}</li>
						<li>Chef: {{ equipe.chef }}</li>
					</ul>
				</li>
			{% empty  %}
				<li>Rien à afficher</li>
			{% endfor %}
		</ul>		
	</div>
	
</div>

{% endblock %}

organisateur/templates/organisateur/liste_participants_niveau1.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Liste de préselection - {{ niveau }}</title>
	<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <link rel="icon" type="image/png" href="{% static 'images/icone.png' %}" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet" />
</head>
<body>
{% include 'organisateur/base_participants_liste_selection.html' %}
</body>
</html>

organisateur/templates/organisateur/nav.eat.html
<div class="font-weight-bold h4">&nbsp;{{ momment_label |capfirst }}</div>
<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'api:global_stats' %}">Général</a>
    </li>
    {% for date in dates %}
    <li class="nav-item">
        <div class="nav-link">
            <a href="{% url 'api:stats' date.jour date.periode %}">({{ date.data.conso }}) {{ date.label |capfirst  }}</a>
            |
            <a href="{% url 'api:stats_liste' date.jour date.periode %}">Liste</a>
        </div>
    </li>
    {% endfor %}
</ul>
<hr>
<div>
    <a href="{% url 'api:orga_eat_history' %}">Suivi des repas l'organisation</a>
</div>