api/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('eat/check/participant/<participant_id>/', views.check_user_eat1, name='check_func'),
    path('eat/check/participant/<jour>/<periode>/<participant_id>/', views.check_user_eat2, name='check_func2'),
    path('eat/register/participant/<jour>/<periode>/<participant_id>/', views.set_user_eat1, name='register_func'),

    path('eat/stats/', views.eat_global_stats, name="global_stats"),
    path('eat/stats/<str:jour>/<str:periode>/', views.eat_stats, name="stats"),
    path('eat/stats/<str:jour>/<str:periode>/liste', views.stats_liste, name="stats_liste"),
    path('eat/stats/orga/', views.orga_eat_history, name="orga_eat_history"),

    path('eat/get/stats/<str:jour>/<str:periode>/', views.get_eat_stats, name="get_stats"),
    path('eat/get/stats/', views.get_global_eat_stats, name="get_global_stats"),


]

organisateur/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'organisateur'
urlpatterns = [
    path('accueil/', views.accueil, name='accueil'),
    path("connexion/", views.connexion, name='connexion'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),


    path('selectiones/listes/repartition',views.liste_re,name='liste_re'),
    path('selectiones/listes/<str:niveau>/',views.liste_se,name='liste_se'),
    path('preselection/listes/<str:niveau>/',views.liste_pre_niveau1,name='liste_pre'),

  	#path('problemes/inscription/', views.inscription_problemes, name='inscription_problemes'),

    path('equipes/<id>/', views.equipe_profil, name='equipe_profil'),
]

participant/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'participant'
urlpatterns = [
    path("connexion/", views.connexion, name='connexion'),
    #path("inscription/", views.inscription, name='inscription'),
    #path('activation/<uidb64>/<token>', views.activate_compte, name='activate'),
    path('<username>/', views.profile, name='profile')

]

technohack/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('@c2e/v2/admin/hack20/', admin.site.urls),
    path('', views.accueil, name="accueil"),
    path('resultats/', views.resultats, name='attente'),
    #path('test/resultats/', views.resultats, name='attente'),

    path('equipes/', views.equipes, name='equipes'),
    path('contact/', views.contact, name='contact'),
    path('participant/', include('participant.urls')),
    path('@c2e/v2/orga/app/', include('organisateur.urls')),
	path('preselections/<str:niveau>/',views.liste_pre_niveau1,name='gb_liste_pre'),

    path('api/',include('api.urls'))

    #path('test/',views.test),
]

templates/accueil.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Technovore Hackathon 2020 | Accueil</title>
    <link rel="icon" type="image/png" href="{% static 'images/icone.png' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet" />
    <style type="text/css">
      html,
      body,
      header,
      .view {
        height: 100%;
      }
      .theme-logo{
        color: #fff;
        padding: 20px;
        font-size: 1.4em;
        box-shadow: 0 2px 5px 0 rgba(0,0,0,.16), 0 2px 10px 0 rgba(0,0,0,.12);
        border-radius: 1px;
        border: 1px solid #fff;
      }
    </style>
  </head>

  <body class="medical-lp">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
        <div class="container">
          <a class="navbar-brand" href="{% url 'accueil' %}"
            ><img
              src="{% static 'images/logoofficiel.png' %}"
              alt=""
              width="150"
              height="auto"
          /></a>

          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!--Links-->
            <ul class="navbar-nav mr-auto smooth-scroll">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accueil' %}"
                  >Accueil <span class="sr-only">(current)</span></a
                >
              </li>

              <li class="nav-item">
                <a
                  class="nav-link font-weight-bolder"
                  href="{% url 'attente' %}"
                  data-offset="80"
                  ><i style="font-size: 5px; vertical-align: middle;"class="fa fa-xs fa-circle text-warning"></i> &nbsp;Résultats des préselections</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'equipes' %}" data-offset="80"
                  >Equipes</a
                >
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}" data-offset="80"
                  >Contactez nous</a
                >
              </li>
            </ul>

            <!--Social Icons-->
            <ul class="navbar-nav nav-flex-icons">
              {% if user.is_authenticated %}
                {% if user.username == 'organisateur' %}
                  <div class="dropdown">
                    <a class="dropdown-toggle white-text" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie" style="font-size:37px;"></i> {{user}}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      
                      <a class="dropdown-item" href="{% url 'organisateur:deconnexion' %}"
                        >Deconnexion</a
                      >
                    </div>
                  </div>
                {% elif user.username == 'admin' %}
                  <div class="dropdown">
                      <a class="dropdown-toggle white-text" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-cog" style="font-size:37px;"></i> {{user}}</a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        
                        <a class="dropdown-item" href="{% url 'organisateur:deconnexion' %}"
                          >Deconnexion</a
                        >
                      </div>
                  </div>
                {% else %}
                  <div class="dropdown">
                    <a class="dropdown-toggle white-text" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-circle" style="font-size:37px;"></i> {{user}}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="{% url 'participant:profile' user %}"
                        >Profile</a
                      >
                      <a class="dropdown-item" href="{% url 'organisateur:deconnexion' %}"
                        >Deconnexion</a
                      >
                    </div>
                  </div>
                {% endif %}
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'participant:connexion' %}"
                  >Connexion</a
                >
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <section
        id="home"
        class="view"
        style="background-image: url('{% static 'images/header.jpg' %}'); background-repeat: no-repeat; background-size: cover; background-position: center center;"
      >       
        <div class="mask mt-sm-3 pt-5">
          <div class="container h-100 align-items-center">
            <div class="row mt-5">
              <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 text-center text-md-left">
                <div class="white-text">
                  <h1
                    class="h1-responsive font-weight-bolder mt-md-5 mt-0 wow fadeInLeft"
                    data-wow-delay="0.3s"
                  >
                   <h1
                    class="mt-5 h1-responsive font-weight-bolder mt-md-5 mt-0 wow fadeInLeft"
                    data-wow-delay="0.3s"
                  >
                    Technovore Hackathon
                  </h1>
                  <hr class="hr-light wow fadeInLeft" data-wow-delay="0.3s" />
                    <div class="h5">Niveau 1: 10 équipes sélectionées sur 19</div>
                    <div class="h5">Niveau 2: 10 équipes sélectionées sur 29</div>
                    <div class="h5">Niveau 3: 6 équipes</div>

                     <!--
                     <a
                    href="{% url 'attente' %}"
                    class="btn mt-4 warning-color-dark font-weight-bold ml-lg-0 wow fadeInLeft white-text"
                    data-wow-delay="0.3s"
                    >Consulter les résultats</a>
                    -->

                </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 wow fadeInLeft" data-wow-delay="0.3s">
                <div class="text-right d-none d-sm-none d-md-block">
                  <img
                    src="{% static 'images/icone.png' %}"
                    alt=""
                    width="400"
                    height="auto"
                    style="display: initial;"
                  />
                </div>
              </div>
            </div>
            <div class="row mt-5"  style="margin-top: 100px;">
            <div class="col-lg-12">
            <div class="d-flex justify-content-around flex-wrap">
              <div>
              <div class="text-center">
                <span class="theme-logo">Data Science | IOT</span>
                <div class="mt-5 text-white">Niveau 2</div>
              </div>
              </div>
              </div>  
            </div>
            <div class="col-lg-12">
              <div class="d-flex justify-content-around flex-wrap">
                <div>
                  <div class="text-center">
                    <span class="theme-logo">3D</span>
                    <div class="mt-5 text-white">Niveau 1</div>
                  </div>
                </div>
                <div>
                <div>
                  <div class="text-center">
                    <span class="theme-logo">IOT</span>
                    <div class="mt-5 text-white">Niveau 3</div>
                  </div>
                </div>
              </div>  
              </div>
            </div>
          </div>
        </div>
      </section>
    </header>
    <script
      type="text/javascript"
      src="{% static 'js/jquery-3.4.1.min.js' %}"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'js/popper.min.js' %}"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'js/bootstrap.min.js' %}"
    ></script>
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <script>
      new WOW().init();
    </script>
  </body>
</html>

templates/attente.html
{% extends 'base.html' %} 

{% block title %}
  Resultats
{% endblock title %}

{% block content %}
{% load static %}
<div
  class="container h2 text-center mx-auto w-100"
  style="position: relative; top:20%"
>
  <div class="col-md wow fadeIn mb-5" data-wow-delay="0.3s">
    <div>
      <img
        src="{% static 'images/icone.png' %}"
        alt=""
        width="150"
        height="auto"
      />
    </div>
  </div>
  <p class="mt-5">
    Les résultats de la préselection ne sont pas encore disponibles
  </p>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <link rel="icon" type="image/png" href="{% static 'images/icone.png' %}" />
    <title>Technovor Hackathon 2020 | {% block title %}{% endblock title %}</title>
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
    />
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet" />
    <style type="text/css">
      html,
      body,
      header,
      .view {
        height: 100%;
      }
    </style>
  </head>

  <body class="medical-lp">
    <!--Navigation & Intro-->

    <!--Navbar-->
    <nav class="navbar elegant-color-dark py-3 navbar-expand-lg navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'accueil' %}"
          ><img
            src="{% static 'images/logoofficiel_blanc.png' %}"
            alt=""
            width="200"
            height="auto"
        /></a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!--Links-->
          <ul class="navbar-nav mr-auto smooth-scroll">
            {% if not user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'accueil' %}"
                >Accueil <span class="sr-only">(current)</span></a
              >
            </li>

            {% endif %}

             <li class="nav-item">
                <a
                  class="nav-link font-weight-bolder"
                  href="{% if user.is_staff %}{% url 'attente' %}{% else %}{% url 'attente' %}{% endif %}"
                  data-offset="80"
                  ><i style="font-size: 5px; vertical-align: middle;"class="fa fa-xs fa-circle text-warning"></i> &nbsp;Résultats des préselections</a>
              </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'equipes' %}" data-offset="80"
                >Equipes</a
              >
            </li>

            {% if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'organisateur:accueil' %}" data-offset="80"
                  >Gestion des équipes</a
                >
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Listes
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'organisateur:liste_se' 'niveau1'%}" target="_blank">Niveau 1 participant sélectionnés</a>
                  <a class="dropdown-item" href="{% url 'organisateur:liste_se' 'niveau2'%}" target="_blank">Niveau 2 participant sélectionnés</a>
                  <a class="dropdown-item" href="{% url 'organisateur:liste_se' 'niveau3'%}" target="_blank">Niveau 3 participant sélectionnés</a>
                  <a class="dropdown-item" href="{% url 'organisateur:liste_se' 'all'%}" target="_blank">Participant sélectionnés</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'organisateur:liste_pre' 'niveau1'%}" target="_blank">Niveau 1 de préselection</a>
                  <a class="dropdown-item" href="{% url 'organisateur:liste_pre' 'niveau2'%}" target="_blank">Niveau 2 de préselection</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'organisateur:liste_re' %}" target="_blank">Liste pour les repartitions</a>
                </div>
              </li>

               <li class="nav-item">
                  <a class="nav-link" href="{% url 'api:global_stats' %}" data-offset="80" target="_blank" 
                    >HackEat</a
                  >
                </li>

              {% if user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}" data-offset="80" target="_blank" 
                    >Administration</a
                  >
                </li>
              {% endif %}

            {% endif %}
           
            {% if not user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}#contact" data-offset="80">Contactez nous</a>
            </li>
            {% endif %}
          </ul>












          <ul class="navbar-nav nav-flex-icons">
            {% if user.is_authenticated %}
                {% if user.username == 'organisateur' %}
                  <div class="dropdown">
                    <a class="dropdown-toggle white-text" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie" style="font-size:37px;"></i> {{user}}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      
                      <a class="dropdown-item" href="{% url 'organisateur:deconnexion' %}"
                        >Deconnexion</a
                      >
                    </div>
                  </div>
                {% elif user.username == 'admin' %}
                  <div class="dropdown">
                      <a class="dropdown-toggle white-text" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-cog" style="font-size:37px;"></i> {{user}}</a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        
                        <a class="dropdown-item" href="{% url 'organisateur:deconnexion' %}"
                          >Deconnexion</a
                        >
                      </div>
                  </div>
                {% else %}
                  <div class="dropdown">
                    <a class="dropdown-toggle white-text" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i> {{user}}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="{% url 'participant:profile' user %}">Profile</a>
                      <a class="dropdown-item" href="{% url 'organisateur:deconnexion' %}">Deconnexion</a>
                    </div>
                  </div>
                {% endif %}
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'participant:connexion' %}"
                >Connexion</a
              >
            </li>

            {% if user.username == "@???@" %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'participant:inscription' %}"
                >Inscription</a
              >
            </li>
            {% endif %}

            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!--/Navbar-->

    <!--Content-->

    {% block content %} {% endblock content %}

    <!--Content-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script
      type="text/javascript"
      src="{% static 'js/jquery-3.4.1.min.js' %}"
    ></script>
    <!-- Bootstrap tooltips -->
    <script
      type="text/javascript"
      src="{% static 'js/popper.min.js' %}"
    ></script>
    <!-- Bootstrap core JavaScript -->
    <script
      type="text/javascript"
      src="{% static 'js/bootstrap.min.js' %}"
    ></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

    <!-- Custom scripts -->
    <script>
      // Animation init
      new WOW().init();
    </script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
    <script>
      $(function(){
        if ($('input').val() != "") {
          $('label[for]').addClass('active')
        }
      })
    </script>
  </body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Contact
{% endblock title %}

{% block content %}
<style type="text/css">
.in-error {
    text-align: left !important;
    color: #ff3547!important;
}
</style>
<div class="container mx-auto justify-content-center my-5">
  <div class="card mx-auto" style="margin-top: 50px;">

    <form id="contact" class="text-center border border-light p-5" method="POST">
      {% csrf_token %}
      <p style="font-size: 60px;"><i class="fas fa-paper-plane"></i></p>
      <p class="h4 mb-4">Contactez nous</p>

      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{message.tags}} alert-dismissible fade show"
        role="alert"
      >
        {{message}}
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %}
      <div class="md-form md-outline">
        <input
          id="name"
          class="form-control"
          name="nom"
          type="text"
          style="line-height: 30px;"
        />
        <label for="name">Nom</label>
        <div class="in-error text-danger">{{ form.nom.errors.0 }}</div>
      </div>
      <div class="md-form md-outline">
        <input
          id="email"
          class="form-control"
          name="email"
          type="email"
          style="line-height: 30px;"
        />
        <label for="email">E-mail</label>
        <div class="in-error text-danger">{{ form.email.errors.0 }}</div>
      </div>
      <div class="md-form md-outline">
        <input
          id="numero"
          class="form-control"
          name="numero"
          type="text"
          style="line-height: 30px;"
        />
        <label for="numero">Numéro de téléphone (Whatsapp)</label>
        <div class="in-error text-danger">{{ form.nom.errors.0 }}</div>
      </div>
      <label>Sujet</label>
      <select class="browser-default custom-select mb-4" required name="sujet">
        <option value="0 xxx" selected>Retour d'information</option>
        <option value="1">Rapport de bug</option>
        <option value="2">Demande de fonctionnalité</option>
      </select>
      <div class="in-error text-danger">{{ form.sujet.errors.0 }}</div>
      <div class="md-form md-outline">
        <textarea
          id="form75"
          class="md-textarea form-control"
          rows="5"
          name="contenu"
        ></textarea>
        <label for="form75">Contenu</label>
        <div class="in-error text-danger">{{ form.contenu.errors.0 }}</div>
      </div>
      <button class="btn btn-info btn-block" type="submit">Envoyer</button>
    </form>
  </div>
</div>
<hr>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Contacts</h3>      
    </div>
  </div>
  <div class="row p-3">
    <div class="col-md-6">
      <div><strong>Téléhpone:</strong></div>
      <div>+255 89 85 28 56</div>
    </div>
    <div class="col-md-6 text-left">
      <div><strong>E-mail:</strong></div>
      <div>c2e.teams@gmail.com</div>
    </div>
  </div>
</div>
{% endblock content %}

templates/contact.old.html
{% extends 'base.html' %}
{% load static %}
<!-- Default form contact -->
{% block title %}
  Contact
{% endblock title %}

{% block content %}
<div class="container mx-auto justify-content-center my-5">
  <div class="card mx-auto" style="margin-top: 50px;">
    <form class="text-center border border-light p-5" method="POST">
      {% csrf_token %}
      <p style="font-size: 60px;"><i class="fas fa-paper-plane"></i></p>
      <p class="h4 mb-4">Contactez nous</p>

      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{message.tags}} alert-dismissible fade show"
        role="alert"
      >
        {{message}}
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %}
      <!-- Name -->
      <div class="md-form md-outline">
        <input
          id="name"
          class="form-control form-control"
          required
          name="nom"
          type="text"
          style="line-height: 30px;"
        />
        <label for="name">Nom</label>
      </div>
      <!-- Email -->
      <div class="md-form md-outline">
        <input
          id="email"
          class="form-control form-control"
          required
          name="email"
          type="email"
          style="line-height: 30px;"
        />
        <label for="email">E-mail</label>
      </div>
      <!-- Subject -->
      <label>Sujet</label>
      <select class="browser-default custom-select mb-4" required name="sujet">
        <option value="" disabled>Choose option</option>
        <option value="0" selected>Retour d'information</option>
        <option value="1">Rapport de bug</option>
        <option value="2">Demande de fonctionnalité</option>
      </select>

      <!-- Message -->
      <!--Material textarea-->
      <div class="md-form md-outline">
        <textarea
          id="form75"
          class="md-textarea form-control"
          rows="5"
          required
          name="message"
        ></textarea>
        <label for="form75">Contenu</label>
      </div>
      <!-- Copy -->
      <div class="custom-control custom-checkbox mb-4">
        <input
          type="checkbox"
          class="custom-control-input"
          id="defaultContactFormCopy"
          name="send_copie"
        />
        <label class="custom-control-label" for="defaultContactFormCopy"
          >M'envoyer une copie de ce message</label
        >
      </div>

      <!-- Send button -->
      <button class="btn btn-info btn-block" type="submit">Envoyer</button>
    </form>
  </div>
  <!-- Default form contact -->
</div>
{% endblock content %}

templates/equipes.html
{% extends 'base.html' %} 
{% block title %}
Liste des equipes
{% endblock title %}

{% block content %}
<div class="container mt-5">
  <div class="my-5 text-center">
    <h2>Liste des équipes</h2>
  </div>
  <div class="col-md-7 mx-auto">
      <!--Filtrer les recherches-->
      <div class="filter mb-5">
        <div class="card py-5 px-5">
          <form method="GET" action="">
            <div class="form-row">
              <div class="form-group col-12">
                <div class="input-group">
                  <input
                    type="search"
                    class="form-control py-2 border-right-0 border"
                    name="participant"
                    placeholder="Participant"
                  />
                  <span class="input-group-append">
                    <div class="input-group-text bg-transparent">
                      <i class="fas fa-search"></i>
                    </div>
                  </span>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-12">
                <div class="input-group">
                  <input
                    type="search"
                    class="form-control py-2 border-right-0 border"
                    name="equipe"
                    placeholder="Equipe"
                  />
                  <span class="input-group-append">
                    <div class="input-group-text bg-transparent">
                      <i class="fas fa-search"></i>
                    </div>
                  </span>
                </div>
              </div>
            </div>
            
            <div class="form-row">
              <div class="form-group col-md">
                <label for="niveau">Niveau</label>
                <select id="niveau" class="form-control" name="niveau">
                  <option selected>Choisir...</option>
                  <option value="Niveau 1">Niveau 1</option>
                  <option value="Niveau 2">Niveau 2</option>
                  <option value="Niveau 3">Niveau 3</option>
                </select>
              </div>
            </div>

            <button
              type="submit"
              style="border-radius: 4px;"
              class="btn btn-primary"
            >
              Chercher
            </button>
            <button
              type="submit"
              style="border-radius: 4px;"
              class="btn btn-danger ml-2"
            >
              Tout
            </button>
          </form>
        </div>
      </div>
    </div>
  <div class="table-responsive-xl text-nowrap">
    <table class="table table-bordered table-dark table-hover">
      <thead>
        <tr class="text-center">
          <th>#</th>
          <th>Equipe</th>
          <th>Membres</th>
          <th>Niveau</th>
          {% if user.is_staff %}
            <th>Actions</th>
          {% endif %}
        </tr>
      </thead>
      <tbody class="text-center">
        {% for equipe in equipes %}
        <tr id="technohack20@equipe-id-{{ equipe.pk }}">
          <td>{{forloop.counter}}</td>
          <td>{{equipe.nom.capitalize}}</td>
          <td>
            <ul style="list-style: none;">
                {% for participant in equipe.participants.all %}
                  {% if participant|lower == equipe.chef|lower %}
                    <li class="text-warning">
                      {{participant.user.last_name.capitalize}}
                      {{participant.user.first_name.capitalize}}
                    </li>
                  {% else %}
                    <li>
                      {{participant.user.last_name.capitalize}}
                      {{participant.user.first_name.capitalize}}
                    </li>
                  {% endif %}
                {% endfor %}
              </ul>
          </td>
          <td>{{equipe.niveau}}</td>
          {% if user.is_staff %}
          <td>
            <a href="{% url 'organisateur:equipe_profil' equipe.pk %}" class="btn btn-sm btn-primary">Afficher</a>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

templates/preselection.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
Liste de préselection - {{ niveau }}
{% endblock title %}
{% block content %}



<div class="container">
	{% include 'organisateur/base_participants_liste_selection.html' %}	
</div>

{% endblock content %}